export type Verb = {
  baseVerb: string;
  pastSimple: string;
  pastParticiple: string;
  translated: string;
};

export const verbs: Verb[] = [
  {
    baseVerb: 'be (is, am, are)',
    pastSimple: 'was, were',
    pastParticiple: 'been',
    translated: 'ser/estar',
  },
  {
    baseVerb: 'beat',
    pastSimple: 'beat',
    pastParticiple: 'beaten',
    translated: 'bater',
  },
  {
    baseVerb: 'become',
    pastSimple: 'became',
    pastParticiple: 'become',
    translated: 'tornar-se',
  },
  {
    baseVerb: 'begin',
    pastSimple: 'began',
    pastParticiple: 'begun',
    translated: 'começar',
  },
  {
    baseVerb: 'bend',
    pastSimple: 'bent',
    pastParticiple: 'bent',
    translated: 'dobrar',
  },
  {
    baseVerb: 'bet',
    pastSimple: 'bet',
    pastParticiple: 'bet',
    translated: 'aposta',
  },
  {
    baseVerb: 'bid',
    pastSimple: 'bid',
    pastParticiple: 'bid',
    translated: 'oferta',
  },
  {
    baseVerb: 'bite',
    pastSimple: 'bit',
    pastParticiple: 'bitten',
    translated: 'bite',
  },
  {
    baseVerb: 'blow',
    pastSimple: 'blew',
    pastParticiple: 'blown',
    translated: 'explodir/estourar',
  },
  {
    baseVerb: 'break',
    pastSimple: 'broke',
    pastParticiple: 'broken',
    translated: 'quebrar/pausa',
  },
  {
    baseVerb: 'bring',
    pastSimple: 'brought',
    pastParticiple: 'brought',
    translated: 'trazer',
  },
  {
    baseVerb: 'build',
    pastSimple: 'built',
    pastParticiple: 'built',
    translated: 'contruir',
  },
  {
    baseVerb: 'burn',
    pastSimple: 'burned/burnt',
    pastParticiple: 'burned/burnt',
    translated: 'queimar',
  },
  {
    baseVerb: 'buy',
    pastSimple: 'bought',
    pastParticiple: 'bought',
    translated: 'comprar',
  },
  {
    baseVerb: 'catch',
    pastSimple: 'caught',
    pastParticiple: 'caught',
    translated: 'apanhar/pegar',
  },
  {
    baseVerb: 'choose',
    pastSimple: 'chose',
    pastParticiple: 'chosen',
    translated: 'escolher',
  },
  {
    baseVerb: 'come',
    pastSimple: 'came',
    pastParticiple: 'come',
    translated: 'vir/venha',
  },
  {
    baseVerb: 'cost',
    pastSimple: 'cost',
    pastParticiple: 'cost',
    translated: 'custo',
  },
  {
    baseVerb: 'cut',
    pastSimple: 'cut',
    pastParticiple: 'cut',
    translated: 'cortar',
  },
  {
    baseVerb: 'dig',
    pastSimple: 'dug',
    pastParticiple: 'dug',
    translated: 'cavar',
  },
  {
    baseVerb: 'dive',
    pastSimple: 'dove',
    pastParticiple: 'dived',
    translated: 'mergulhar',
  },
  {
    baseVerb: 'do',
    pastSimple: 'did',
    pastParticiple: 'done',
    translated: 'fazer',
  },
  {
    baseVerb: 'draw',
    pastSimple: 'drew',
    pastParticiple: 'drawn',
    translated: 'desenhar',
  },
  {
    baseVerb: 'dream',
    pastSimple: 'dreamed/dreamt',
    pastParticiple: 'dreamed/dreamt',
    translated: 'sonhar',
  },
  {
    baseVerb: 'drive',
    pastSimple: 'drove',
    pastParticiple: 'driven',
    translated: 'dirigir',
  },
  {
    baseVerb: 'drink',
    pastSimple: 'drank',
    pastParticiple: 'drunk',
    translated: 'beber',
  },
  {
    baseVerb: 'eat',
    pastSimple: 'ate',
    pastParticiple: 'eaten',
    translated: 'comer',
  },
  {
    baseVerb: 'fall',
    pastSimple: 'fell',
    pastParticiple: 'fallen',
    translated: 'cair',
  },
  {
    baseVerb: 'feel',
    pastSimple: 'felt',
    pastParticiple: 'felt',
    translated: 'sentir',
  },
  {
    baseVerb: 'fight',
    pastSimple: 'fought',
    pastParticiple: 'fought',
    translated: 'lutar',
  },
  {
    baseVerb: 'find',
    pastSimple: 'found',
    pastParticiple: 'found',
    translated: 'encontrar',
  },
  {
    baseVerb: 'fly',
    pastSimple: 'flew',
    pastParticiple: 'flown',
    translated: 'voar',
  },
  {
    baseVerb: 'forget',
    pastSimple: 'forgot',
    pastParticiple: 'forgotten',
    translated: 'esquecer',
  },
  {
    baseVerb: 'forgive',
    pastSimple: 'forgave',
    pastParticiple: 'forgiven',
    translated: 'perdoar',
  },
  {
    baseVerb: 'freeze',
    pastSimple: 'froze',
    pastParticiple: 'frozen',
    translated: 'congelar',
  },
  {
    baseVerb: 'get',
    pastSimple: 'got',
    pastParticiple: 'gotten',
    translated: 'obter',
  },
  {
    baseVerb: 'give',
    pastSimple: 'gave',
    pastParticiple: 'given',
    translated: 'dar',
  },
  {
    baseVerb: 'go',
    pastSimple: 'went',
    pastParticiple: 'gone',
    translated: 'ir',
  },
  {
    baseVerb: 'grow',
    pastSimple: 'grew',
    pastParticiple: 'grown',
    translated: 'crescer',
  },
  {
    baseVerb: 'hang',
    pastSimple: 'hung',
    pastParticiple: 'hung',
    translated: 'pendurar',
  },
  {
    baseVerb: 'have',
    pastSimple: 'had',
    pastParticiple: 'had',
    translated: 'ter',
  },
  {
    baseVerb: 'hear',
    pastSimple: 'heard',
    pastParticiple: 'heard',
    translated: 'ouvir',
  },
  {
    baseVerb: 'hide',
    pastSimple: 'hid',
    pastParticiple: 'hidden',
    translated: 'esconder',
  },
  {
    baseVerb: 'hit',
    pastSimple: 'hit',
    pastParticiple: 'hit',
    translated: 'bater',
  },
  {
    baseVerb: 'hold',
    pastSimple: 'held',
    pastParticiple: 'held',
    translated: 'celebrar',
  },
  {
    baseVerb: 'hurt',
    pastSimple: 'hurt',
    pastParticiple: 'hurt',
    translated: 'machucar',
  },
  {
    baseVerb: 'keep',
    pastSimple: 'kept',
    pastParticiple: 'kept',
    translated: 'manter',
  },
  {
    baseVerb: 'know',
    pastSimple: 'knew',
    pastParticiple: 'known',
    translated: 'saber',
  },
  {
    baseVerb: 'lay',
    pastSimple: 'laid',
    pastParticiple: 'laid',
    translated: 'colocar',
  },
  {
    baseVerb: 'lead',
    pastSimple: 'led',
    pastParticiple: 'led',
    translated: 'conduzir/levar',
  },
  {
    baseVerb: 'leave',
    pastSimple: 'left',
    pastParticiple: 'left',
    translated: 'deixar',
  },
  {
    baseVerb: 'lend',
    pastSimple: 'lent',
    pastParticiple: 'lent',
    translated: 'emprestar',
  },
  {
    baseVerb: 'let',
    pastSimple: 'let',
    pastParticiple: 'let',
    translated: 'deixar/permitir',
  },
  {
    baseVerb: 'lie',
    pastSimple: 'lay',
    pastParticiple: 'lain',
    translated: 'mentir',
  },
  {
    baseVerb: 'lose',
    pastSimple: 'lost',
    pastParticiple: 'lost',
    translated: 'perder',
  },
  {
    baseVerb: 'make',
    pastSimple: 'made',
    pastParticiple: 'made',
    translated: 'fazer',
  },
  {
    baseVerb: 'mean',
    pastSimple: 'meant',
    pastParticiple: 'meant',
    translated: 'quer-dizer/significar',
  },
  {
    baseVerb: 'meet',
    pastSimple: 'met',
    pastParticiple: 'met',
    translated: 'conhecer/encontrar',
  },
  {
    baseVerb: 'pay',
    pastSimple: 'paid',
    pastParticiple: 'paid',
    translated: 'pagar',
  },
  {
    baseVerb: 'put',
    pastSimple: 'put',
    pastParticiple: 'put',
    translated: 'colocar',
  },
  {
    baseVerb: 'read',
    pastSimple: 'read',
    pastParticiple: 'read',
    translated: 'ler',
  },
  {
    baseVerb: 'ride',
    pastSimple: 'rode',
    pastParticiple: 'ridden',
    translated: 'pilotar',
  },
  {
    baseVerb: 'ring',
    pastSimple: 'rang',
    pastParticiple: 'rung',
    translated: 'badalar',
  },
  {
    baseVerb: 'rise',
    pastSimple: 'rose',
    pastParticiple: 'risen',
    translated: 'subir/aumentar',
  },
  {
    baseVerb: 'run',
    pastSimple: 'ran',
    pastParticiple: 'run',
    translated: 'correr',
  },
  {
    baseVerb: 'say',
    pastSimple: 'said',
    pastParticiple: 'said',
    translated: 'dizer',
  },
  {
    baseVerb: 'see',
    pastSimple: 'saw',
    pastParticiple: 'seen',
    translated: 'ver',
  },
  {
    baseVerb: 'sell',
    pastSimple: 'sold',
    pastParticiple: 'sold',
    translated: 'vender',
  },
  {
    baseVerb: 'send',
    pastSimple: 'sent',
    pastParticiple: 'sent',
    translated: 'enviar',
  },
  {
    baseVerb: 'show',
    pastSimple: 'showed',
    pastParticiple: 'shown',
    translated: 'mostrar',
  },
  {
    baseVerb: 'shut',
    pastSimple: 'shut',
    pastParticiple: 'shut',
    translated: 'fechar/calar',
  },
  {
    baseVerb: 'sing',
    pastSimple: 'sang',
    pastParticiple: 'sung',
    translated: 'cantar',
  },
  {
    baseVerb: 'sit',
    pastSimple: 'sat',
    pastParticiple: 'sat',
    translated: 'sentar',
  },
  {
    baseVerb: 'sleep',
    pastSimple: 'slept',
    pastParticiple: 'slept',
    translated: 'dormir',
  },
  {
    baseVerb: 'speak',
    pastSimple: 'spoke',
    pastParticiple: 'spoken',
    translated: 'falar',
  },
  {
    baseVerb: 'spend',
    pastSimple: 'spent',
    pastParticiple: 'spent',
    translated: 'gastar',
  },
  {
    baseVerb: 'stand',
    pastSimple: 'stood',
    pastParticiple: 'stood',
    translated: 'permanecer/ficar',
  },
  {
    baseVerb: 'swim',
    pastSimple: 'swam',
    pastParticiple: 'swum',
    translated: 'nadar',
  },
  {
    baseVerb: 'take',
    pastSimple: 'took',
    pastParticiple: 'taken',
    translated: 'pegar',
  },
  {
    baseVerb: 'teach',
    pastSimple: 'taught',
    pastParticiple: 'taught',
    translated: 'ensinar',
  },
  {
    baseVerb: 'tear',
    pastSimple: 'tore',
    pastParticiple: 'torn',
    translated: 'rasgar',
  },
  {
    baseVerb: 'tell',
    pastSimple: 'told',
    pastParticiple: 'told',
    translated: 'dizer',
  },
  {
    baseVerb: 'think',
    pastSimple: 'thought',
    pastParticiple: 'thought',
    translated: 'pensar',
  },
  {
    baseVerb: 'throw',
    pastSimple: 'threw',
    pastParticiple: 'thrown',
    translated: 'jogar',
  },
  {
    baseVerb: 'understand',
    pastSimple: 'understood',
    pastParticiple: 'understood',
    translated: 'entender',
  },
  {
    baseVerb: 'wake',
    pastSimple: 'woke',
    pastParticiple: 'woken',
    translated: 'andar',
  },
  {
    baseVerb: 'wear',
    pastSimple: 'wore',
    pastParticiple: 'worn',
    translated: 'vestir',
  },
  {
    baseVerb: 'win',
    pastSimple: 'won',
    pastParticiple: 'won',
    translated: 'ganhar',
  },
  {
    baseVerb: 'write',
    pastSimple: 'wrote',
    pastParticiple: 'written',
    translated: 'escrever',
  },
];
