export const verbs = [
  {
    baseVerb: "be (is, am, are)",
    pastSimple: "was, were",
    pastParticiple: "been",
    Translated: "ser/estar",
  },
  {
    baseVerb: "beat",
    pastSimple: "beat",
    pastParticiple: "beaten",
    Translated: "bater",
  },
  {
    baseVerb: "become",
    pastSimple: "became",
    pastParticiple: "become",
    Translated: "tornar-se",
  },
  {
    baseVerb: "begin",
    pastSimple: "began",
    pastParticiple: "begun",
    Translated: "começar",
  },
  {
    baseVerb: "bend",
    pastSimple: "bent",
    pastParticiple: "bent",
    Translated: "dobrar",
  },
  {
    baseVerb: "bet",
    pastSimple: "bet",
    pastParticiple: "bet",
    Translated: "aposta",
  },
  {
    baseVerb: "bid",
    pastSimple: "bid",
    pastParticiple: "bid",
    Translated: "oferta",
  },
  {
    baseVerb: "bite",
    pastSimple: "bit",
    pastParticiple: "bitten",
    Translated: "bite",
  },
  {
    baseVerb: "blow",
    pastSimple: "blew",
    pastParticiple: "blown",
    Translated: "explodir/estourar",
  },
  {
    baseVerb: "break",
    pastSimple: "broke",
    pastParticiple: "broken",
    Translated: "quebrar/pausa",
  },
  {
    baseVerb: "bring",
    pastSimple: "brought",
    pastParticiple: "brought",
    Translated: "trazer",
  },
  {
    baseVerb: "build",
    pastSimple: "built",
    pastParticiple: "built",
    Translated: "contruir",
  },
  {
    baseVerb: "burn",
    pastSimple: "burned/burnt",
    pastParticiple: "burned/burnt",
    Translated: "queimar",
  },
  {
    baseVerb: "buy",
    pastSimple: "bought",
    pastParticiple: "bought",
    Translated: "comprar",
  },
  {
    baseVerb: "catch",
    pastSimple: "caught",
    pastParticiple: "caught",
    Translated: "apanhar/pegar",
  },
  {
    baseVerb: "choose",
    pastSimple: "chose",
    pastParticiple: "chosen",
    Translated: "escolher",
  },
  {
    baseVerb: "come",
    pastSimple: "came",
    pastParticiple: "come",
    Translated: "vir/venha",
  },
  {
    baseVerb: "cost",
    pastSimple: "cost",
    pastParticiple: "cost",
    Translated: "custo",
  },
  {
    baseVerb: "cut",
    pastSimple: "cut",
    pastParticiple: "cut",
    Translated: "cortar",
  },
  {
    baseVerb: "dig",
    pastSimple: "dug",
    pastParticiple: "dug",
    Translated: "cavar",
  },
  {
    baseVerb: "dive",
    pastSimple: "dove",
    pastParticiple: "dived",
    Translated: "mergulhar",
  },
  {
    baseVerb: "do",
    pastSimple: "did",
    pastParticiple: "done",
    Translated: "fazer",
  },
  {
    baseVerb: "draw",
    pastSimple: "drew",
    pastParticiple: "drawn",
    Translated: "desenhar",
  },
  {
    baseVerb: "dream",
    pastSimple: "dreamed/dreamt",
    pastParticiple: "dreamed/dreamt",
    Translated: "sonhar",
  },
  {
    baseVerb: "drive",
    pastSimple: "drove",
    pastParticiple: "driven",
    Translated: "dirigir",
  },
  {
    baseVerb: "drink",
    pastSimple: "drank",
    pastParticiple: "drunk",
    Translated: "beber",
  },
  {
    baseVerb: "eat",
    pastSimple: "ate",
    pastParticiple: "eaten",
    Translated: "comer",
  },
  {
    baseVerb: "fall",
    pastSimple: "fell",
    pastParticiple: "fallen",
    Translated: "cair",
  },
  {
    baseVerb: "feel",
    pastSimple: "felt",
    pastParticiple: "felt",
    Translated: "sentir",
  },
  {
    baseVerb: "fight",
    pastSimple: "fought",
    pastParticiple: "fought",
    Translated: "lutar",
  },
  {
    baseVerb: "find",
    pastSimple: "found",
    pastParticiple: "found",
    Translated: "encontrar",
  },
  {
    baseVerb: "fly",
    pastSimple: "flew",
    pastParticiple: "flown",
    Translated: "voar",
  },
  {
    baseVerb: "forget",
    pastSimple: "forgot",
    pastParticiple: "forgotten",
    Translated: "esquecer",
  },
  {
    baseVerb: "forgive",
    pastSimple: "forgave",
    pastParticiple: "forgiven",
    Translated: "perdoar",
  },
  {
    baseVerb: "freeze",
    pastSimple: "froze",
    pastParticiple: "frozen",
    Translated: "congelar",
  },
  {
    baseVerb: "get",
    pastSimple: "got",
    pastParticiple: "gotten",
    Translated: "obter",
  },
  {
    baseVerb: "give",
    pastSimple: "gave",
    pastParticiple: "given",
    Translated: "dar",
  },
  {
    baseVerb: "go",
    pastSimple: "went",
    pastParticiple: "gone",
    Translated: "ir",
  },
  {
    baseVerb: "grow",
    pastSimple: "grew",
    pastParticiple: "grown",
    Translated: "crescer",
  },
  {
    baseVerb: "hang",
    pastSimple: "hung",
    pastParticiple: "hung",
    Translated: "pendurar",
  },
  {
    baseVerb: "have",
    pastSimple: "had",
    pastParticiple: "had",
    Translated: "ter",
  },
  {
    baseVerb: "hear",
    pastSimple: "heard",
    pastParticiple: "heard",
    Translated: "ouvir",
  },
  {
    baseVerb: "hide",
    pastSimple: "hid",
    pastParticiple: "hidden",
    Translated: "esconder",
  },
  {
    baseVerb: "hit",
    pastSimple: "hit",
    pastParticiple: "hit",
    Translated: "bater",
  },
  {
    baseVerb: "hold",
    pastSimple: "held",
    pastParticiple: "held",
    Translated: "celebrar",
  },
  {
    baseVerb: "hurt",
    pastSimple: "hurt",
    pastParticiple: "hurt",
    Translated: "machucar",
  },
  {
    baseVerb: "keep",
    pastSimple: "kept",
    pastParticiple: "kept",
    Translated: "manter",
  },
  {
    baseVerb: "know",
    pastSimple: "knew",
    pastParticiple: "known",
    Translated: "saber",
  },
  {
    baseVerb: "lay",
    pastSimple: "laid",
    pastParticiple: "laid",
    Translated: "colocar",
  },
  {
    baseVerb: "lead",
    pastSimple: "led",
    pastParticiple: "led",
    Translated: "conduzir/levar",
  },
  {
    baseVerb: "leave",
    pastSimple: "left",
    pastParticiple: "left",
    Translated: "deixar",
  },
  {
    baseVerb: "lend",
    pastSimple: "lent",
    pastParticiple: "lent",
    Translated: "emprestar",
  },
  {
    baseVerb: "let",
    pastSimple: "let",
    pastParticiple: "let",
    Translated: "deixar/permitir",
  },
  {
    baseVerb: "lie",
    pastSimple: "lay",
    pastParticiple: "lain",
    Translated: "mentir",
  },
  {
    baseVerb: "lose",
    pastSimple: "lost",
    pastParticiple: "lost",
    Translated: "perder",
  },
  {
    baseVerb: "make",
    pastSimple: "made",
    pastParticiple: "made",
    Translated: "fazer",
  },
  {
    baseVerb: "mean",
    pastSimple: "meant",
    pastParticiple: "meant",
    Translated: "quer-dizer/significar",
  },
  {
    baseVerb: "meet",
    pastSimple: "met",
    pastParticiple: "met",
    Translated: "conhecer/encontrar",
  },
  {
    baseVerb: "pay",
    pastSimple: "paid",
    pastParticiple: "paid",
    Translated: "pagar",
  },
  {
    baseVerb: "put",
    pastSimple: "put",
    pastParticiple: "put",
    Translated: "colocar",
  },
  {
    baseVerb: "read",
    pastSimple: "read",
    pastParticiple: "read",
    Translated: "ler",
  },
  {
    baseVerb: "ride",
    pastSimple: "rode",
    pastParticiple: "ridden",
    Translated: "pilotar",
  },
  {
    baseVerb: "ring",
    pastSimple: "rang",
    pastParticiple: "rung",
    Translated: "badalar",
  },
  {
    baseVerb: "rise",
    pastSimple: "rose",
    pastParticiple: "risen",
    Translated: "subir/aumentar",
  },
  {
    baseVerb: "run",
    pastSimple: "ran",
    pastParticiple: "run",
    Translated: "correr",
  },
  {
    baseVerb: "say",
    pastSimple: "said",
    pastParticiple: "said",
    Translated: "dizer",
  },
  {
    baseVerb: "see",
    pastSimple: "saw",
    pastParticiple: "seen",
    Translated: "ver",
  },
  {
    baseVerb: "sell",
    pastSimple: "sold",
    pastParticiple: "sold",
    Translated: "vender",
  },
  {
    baseVerb: "send",
    pastSimple: "sent",
    pastParticiple: "sent",
    Translated: "enviar",
  },
  {
    baseVerb: "show",
    pastSimple: "showed",
    pastParticiple: "shown",
    Translated: "mostrar",
  },
  {
    baseVerb: "shut",
    pastSimple: "shut",
    pastParticiple: "shut",
    Translated: "fechar/calar",
  },
  {
    baseVerb: "sing",
    pastSimple: "sang",
    pastParticiple: "sung",
    Translated: "cantar",
  },
  {
    baseVerb: "sit",
    pastSimple: "sat",
    pastParticiple: "sat",
    Translated: "sentar",
  },
  {
    baseVerb: "sleep",
    pastSimple: "slept",
    pastParticiple: "slept",
    Translated: "dormir",
  },
  {
    baseVerb: "speak",
    pastSimple: "spoke",
    pastParticiple: "spoken",
    Translated: "falar",
  },
  {
    baseVerb: "spend",
    pastSimple: "spent",
    pastParticiple: "spent",
    Translated: "gastar",
  },
  {
    baseVerb: "stand",
    pastSimple: "stood",
    pastParticiple: "stood",
    Translated: "permanecer/ficar",
  },
  {
    baseVerb: "swim",
    pastSimple: "swam",
    pastParticiple: "swum",
    Translated: "nadar",
  },
  {
    baseVerb: "take",
    pastSimple: "took",
    pastParticiple: "taken",
    Translated: "pegar",
  },
  {
    baseVerb: "teach",
    pastSimple: "taught",
    pastParticiple: "taught",
    Translated: "ensinar",
  },
  {
    baseVerb: "tear",
    pastSimple: "tore",
    pastParticiple: "torn",
    Translated: "rasgar",
  },
  {
    baseVerb: "tell",
    pastSimple: "told",
    pastParticiple: "told",
    Translated: "dizer",
  },
  {
    baseVerb: "think",
    pastSimple: "thought",
    pastParticiple: "thought",
    Translated: "pensar",
  },
  {
    baseVerb: "throw",
    pastSimple: "threw",
    pastParticiple: "thrown",
    Translated: "jogar",
  },
  {
    baseVerb: "understand",
    pastSimple: "understood",
    pastParticiple: "understood",
    Translated: "entender",
  },
  {
    baseVerb: "wake",
    pastSimple: "woke",
    pastParticiple: "woken",
    Translated: "andar",
  },
  {
    baseVerb: "wear",
    pastSimple: "wore",
    pastParticiple: "worn",
    Translated: "vestir",
  },
  {
    baseVerb: "win",
    pastSimple: "won",
    pastParticiple: "won",
    Translated: "ganhar",
  },
  {
    baseVerb: "write",
    pastSimple: "wrote",
    pastParticiple: "written",
    Translated: "escrever",
  },
];
