import type { NextPage } from 'next';
import Head from 'next/head';

import { Container, Header, Title } from '@/styles/home';
import MiddleContainer from '@/components/MiddleContainer';
import { verbs, Verb } from '@/constants/verbs';
import useCountdown from '@/hooks/useCountdown';
import { useEffect, useState } from 'react';

const Home: NextPage = () => {
  const { minutes, seconds } = useCountdown();
  const timeTitleMiddleContainer = `${String(minutes).padStart(2, '0')}:${String(seconds).padStart(2, '0')}`;

  const [currentVerbIndex, setCurrentVerbIndex] = useState(0);
  const [currentVerb, setCurrentVerb] = useState<Verb | null>(null);

  useEffect(() => {
    if (minutes === 0 && seconds === 0) {
      setCurrentVerbIndex((prevState) => {
        if (prevState === verbs.length) {
          return 0;
        }
        return prevState + 1;
      })
    }
  }, [minutes, seconds])

  useEffect(() => {
    setCurrentVerb(verbs[currentVerbIndex])
  }, [currentVerbIndex]);

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Title>ENGLISHING</Title>
      </Header>

      {currentVerb && (
        <MiddleContainer title={timeTitleMiddleContainer} verb={currentVerb} />
      )}
    </Container>
  );
};

export default Home;
