import type { NextPage } from 'next';
import Head from 'next/head';

import { Container, Header, Title } from '@/styles/home';
import MiddleContainer from '@/components/MiddleContainer';
import { verbs } from '@/constants/verbs';
const Home: NextPage = () => {
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Title>ENGLISHING</Title>
      </Header>

      <MiddleContainer title="2:35" verb={verbs[0]} />
    </Container>
  );
};

export default Home;
